export const MarketData = [
  {
    "id": 1,
    "image" :"/service/dell1.jpg",
    "image2":"/service/dell2.jpg",
    "title": "Dell Laptop",
    "status":"For Sale",
    "price":"N500K",
    "features":"11th Gen core i8 1trb ssd 32G",
    "condition":"Clean Used",
    "inventory":"1",
    "tag":"Electronics and Gadgets",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 2,
    "image" :"/service/panel1.jpg",
    "image2":"/service/panel2.jpg",
    "title": "Solar Panels",
    "status":"For Sale",
    "price":"N1.5M - N3.3M",
    "features":"lithium core",
    "condition":"New",
    "inventory":"stocked",
    "tag":"Electronics and Gadgets",
    "country": "Nigeria",
    "state":"Niger",
    "area":"Mokwa",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 3,
    "image" :"/service/projector1.jpg",
    "image2":"/service/projector2.jpg",
    "title": "Projectors",
    "status":"For Lease",
    "price":"N1k per Hour",
    "features":"high resolution HD",
    "condition":"fairly used",
    "inventory":"3",
    "tag":"Electronics and Gadgets",
    "country": "Nigeria",
    "state":"Kano",
    "area":"Dawakin kudo",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 4,
    "image" :"/service/camera1.jpg",
    "image2":"/service/camera2.jpg",
    "title": "Camera",
    "status":"For Lease",
    "price":"N1.5k per hour",
    "features":"Red Dragon",
    "condition":"very used",
    "inventory":"5",
    "tag":"Electronics and Gadgets",
    "country": "Nigeria",
    "state":"Kano",
    "area":"Dawakin kudo",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 5,
    "image" :"/service/drill2.jpg",
    "image2":"/service/drill3.jpg",
    "title": "Power Drill",
    "status":"For Sale",
    "price":"N30k",
    "features":"Russian Made",
    "condition":"New",
    "inventory":"30",
    "tag":"Tools and Hardwares",
    "country": "Nigeria",
    "state":"Niger",
    "area":"Mokwa",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only", 
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",   
  },
  {
    "id": 6,
    "image" :"/service/fs3.jpg",
    "image2":"/service/fs6.jpg",
    "title": "Brown Shoe",
    "status":"For Sale",
    "price":"N40000",
    "features":"skin",
    "condition":"new",
    "inventory":"5",
    "tag":"Fashion",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 7,
    "image" :"/service/bounce1.jpg",
    "image2":"/service/bounce2.jpg",
    "title": "bounce houses",
    "status":"For Lease",
    "price":"N2k per Hour",
    "features":"50 by 50 Square Meter",
    "condition":"clean Used",
    "inventory":"3",
    "tag":"Sports and Outdoors",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"Lokoja",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt", 
  },
  {
    "id": 8,
    "image" :"/service/fc1.jpg",
    "image2":"/service/fc2.jpg",
    "title": "Black Face Cap",
    "status":"For Sale",
    "price":"N5000",
    "features":"cotton 100%",
    "condition":"new",
    "inventory":"1",
    "tag":"Fashion",
    "country": "Nigeria",
    "state":"Niger",
    "area":"Agaye",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 9,
    "image" :"/service/fcc2.jpg",
    "image2":"/service/fcc3.jpg",
    "title": "Pain T shirt",
    "status":"For Sale",
    "price":"N3000",
    "features":"pure cotton",
    "condition":"New",
    "inventory":"stocked",
    "tag":"Fashion",
    "country": "Nigeria",
    "state":"Kano",
    "area":"B.U.K Road",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 10,
    "image" :"/service/fs1.jpg",
    "image2":"/service/fs2.jpg",
    "title": "black shoe",
    "status":"For sale",
    "price":"N35000",
    "features":"leather",
    "condition":"New",
    "inventory":"3",
    "tag":"Fashion",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 11,
    "image" :"/service/ft1.jpg",
    "image2":"/service/ft2.jpg",
    "title": "Blue Jeans",
    "status":"For Sale",
    "price":"N3000",
    "features":"Russian Made",
    "condition":"New",
    "inventory":"30",
    "tag":"Fashion",
    "country": "Nigeria",
    "state":"Niger",
    "area":"Suleja",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
   
  },
  {
    "id": 12,
    "image" :"/service/ft3.jpg",
    "image2":"/service/ft4.jpg",
    "title": "Used Jeans",
    "status":"For Sale",
    "price":"N1500",
    "features":"blue jeans",
    "condition":"clean Used",
    "inventory":"syocked",
    "tag":"Fashion",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"Kotokarfey",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },

  {
    "id": 13,
    "image" :"/service/fcl1.jpg",
    "image2":"/service/fcl2.jpg",
    "title": "Black Pain T shirt",
    "status":"For Sale",
    "price":"N3000",
    "features":"pure cotton",
    "condition":"New",
    "inventory":"stocked",
    "tag":"Fashion",
    "country": "Nigeria",
    "state":"Niger",
    "area":"Kpagungu",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 14,
    "image" :"/service/drill1.jpg",
    "image2":"/service/drill2.jpg",
    "title": "Power Drill",
    "status":"For Lease",
    "price":"N500 per hour",
    "features":"made in Russia",
    "condition":"clean used",
    "inventory":"4",
    "tag":"Tools and Hardwares",
    "country": "Nigeria",
    "state":"Kano",
    "area":"Wudil",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",  
  },
  {
    "id": 15,
    "image" :"/service/fc1.jpg",
    "image2":"/service/fc2.jpg",
    "title": "Black Face Cap",
    "status":"For Sale",
    "price":"N5000",
    "features":"cotton 100%",
    "condition":"new",
    "inventory":"1",
    "tag":"Fashion",
    "country": "Nigeria",
    "state":"Kano",
    "area":"Kofa Shakir",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 16,
    "image" :"/service/fish1.jpg",
    "image2":"/service/fish2.jpg",
    "title": "Ice Fish",
    "status":"For Sale",
    "price":"N1500 per kg",
    "features":"titus fish",
    "condition":"fresh",
    "inventory":"stoced",
    "tag":"Food and Provisions",
    "country": "Nigeria",
    "state":"Niger",
    "area":"Mokwa",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 17,
    "image" :"/service/bis1.jpg",
    "image2":"/service/bis2.jpg",
    "title": "Biscuit",
    "status":"For Sale",
    "price":"N2500 per pack",
    "features":"10 pis",
    "condition":"New",
    "inventory":"stocked",
    "tag":"Food and Provisions",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 18,
    "image" :"/service/meat1.jpg",
    "image2":"/service/meat2.jpg",
    "title": "Beaf",
    "status":"For sale",
    "price":"N1500 per kg",
    "features":"red meat halal",
    "condition":"fresh",
    "inventory":"stocked",
    "tag":"Food and Provisions",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 19,
    "image" :"/service/milk1.jpg",
    "image2":"/service/milk2.jpg",
    "title": "Milk Drink",
    "status":"For Sale",
    "price":"N300",
    "features":"meji milk",
    "condition":"fresh",
    "inventory":"30",
    "tag":"Food and Provisions",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
   
  },
  {
    "id": 20,
    "image" :"/service/milo1.jpg",
    "image2":"/service/milo.jpg",
    "title": "Milo",
    "status":"For Sale",
    "price":"N5000",
    "features":"nestle 500g",
    "condition":"new",
    "inventory":"14",
    "tag":"Food and Provisions",
    "country": "Nigeria",
    "state":"Kano",
    "area":"Dawakin kudo",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 21,
    "image" :"/service/rice1.jpg",
    "image2":"/service/rice2.jpg",
    "title": "Basmatic Rice",
    "status":"For Sale",
    "price":"N50000",
    "features":"Royal",
    "condition":"fresh",
    "inventory":"stock",
    "tag":"Food and Provisions",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 22,
    "image" :"/service/sos1.jpg",
    "image2":"/service/sos2.jpg",
    "title": "sosage",
    "status":"For Sale",
    "price":"N5000",
    "features":"Jonhsonville",
    "condition":"fresh",
    "inventory":"stock",
    "tag":"Food and Provisions",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 23,
    "image" :"/service/t1.jpg",
    "image2":"/service/t2.jpg",
    "title": "Black toy Benz",
    "status":"For Sale",
    "price":"N150000",
    "features":"Russian Made",
    "condition":"New",
    "inventory":"13",
    "tag":"Toys and Games",
    "country": "Nigeria",
    "state":"Kano",
    "area":"Dawakin kudo",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 24,
    "image" :"/service/t3.jpg",
    "image2":"/service/t4.jpg",
    "title": "White toy Car Benz",
    "status":"For Sale",
    "price":"N150000",
    "features":"Turkey Made",
    "condition":"New",
    "inventory":"stocked",
    "tag":"Toys and Games",
    "country": "Nigeria",
    "state":"Niger",
    "area":"Mokwa",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 25,
    "image" :"/service/tb1.jpg",
    "image2":"/service/tb2.jpg",
    "title": "Bicycle",
    "status":"For Slae",
    "price":"N70000",
    "features":"Made in China",
    "condition":"New",
    "inventory":"13",
    "tag":"Toys and Games",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 26,
    "image" :"/service/tsh1.jpg",
    "image2":"/service/tsh2.jpg",
    "title": "Roller-Skate",
    "status":"For Sale",
    "price":"N40000",
    "features":"Made in China",
    "condition":"New",
    "inventory":"5",
    "tag":"Toys and Games",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"Ajakota",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 27,
    "image" :"/service/tsr1.jpg",
    "image2":"/service/tsr2.jpg",
    "title": "skipping rope",
    "status":"For Sale",
    "price":"N3000",
    "features":"Russian Made",
    "condition":"New",
    "inventory":"30",
    "tag":"Toys and Games",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"Kotokarfey",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 28,
    "image" :"/service/tsw1.jpg",
    "image2":"/service/tsw2.jpg",
    "title": "Nitendo Switch",
    "status":"For Sale",
    "price":"N250000",
    "features":"made in China",
    "condition":"New",
    "inventory":"4",
    "tag":"Toys and Games",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 29,
    "image" :"/service/bounce1.jpg",
    "image2":"/service/bounce2.jpg",
    "title": "bounce houses",
    "status":"For Lease",
    "price":"N2k per Hour",
    "features":"50 by 50 Square Meter",
    "condition":"clean Used",
    "inventory":"3",
    "tag":"Sports and Outdoors",
    "country": "Nigeria",
    "state":"Kano",
    "area":"Dawakin kudo",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 30,
    "image" :"/service/d44.jpg",
    "image2":"/service/d4.jpg",
    "title": "Door",
    "status":"For Sale",
    "price":"N500K",
    "features":"made in Nigeria",
    "condition":"New",
    "inventory":"11",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Niger",
    "area":"Kpagungu",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 31,
    "image" :"/service/d33.jpg",
    "image2":"/service/d3.jpg",
    "title": "Bullet Proof Door",
    "status":"For Sale",
    "price":"N1.5M - N3.3M",
    "features":"heavy Proof Door",
    "condition":"New",
    "inventory":"stocked",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Niger",
    "area":"Agaye",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 32,
    "image" :"/service/d1.jpg",
    "image2":"/service/d2.jpg",
    "title": "Steel Door",
    "status":"For Sale",
    "price":"N100000",
    "features":"high resolution HD",
    "condition":"New",
    "inventory":"31",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 33,
    "image" :"/service/bssk1.jpg",
    "image2":"/service/bssk2.jpg",
    "title": "Sink",
    "status":"For Sale",
    "price":"N51000",
    "features":"ceramics and Wood",
    "condition":"New",
    "inventory":"5",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Kano",
    "area":"Dawakin kudo",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 34,
    "image" :"/service/bsst1.jpg",
    "image2":"/service/bsst2.jpg",
    "title": "Toilet Setter",
    "status":"For Sale",
    "price":"N70000",
    "features":"Russian Made",
    "condition":"New",
    "inventory":"30",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Kano",
    "area":"Wudil",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 35,
    "image" :"/service/bw1.jpg",
    "image2":"/service/bw2.jpg",
    "title": "window push",
    "status":"For sale",
    "price":"N15000",
    "features":"made in Russia",
    "condition":"new",
    "inventory":"4",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Niger",
    "area":"Suleja",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 36,
    "image" :"/service/bw3.jpg",
    "image2":"/service/bw4.jpg",
    "title": "window open",
    "status":"For sale",
    "price":"N20000",
    "features":"glass and steel",
    "condition":"New",
    "inventory":"33",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 37,
    "image" :"/service/bsst3.jpg",
    "image2":"/service/bsst4.jpg",
    "title": "Turkey Toilet setter",
    "status":"For Sale",
    "price":"N500K",
    "features":"11th Gen Turk",
    "condition":"New",
    "inventory":"110",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt"
  },
  {
    "id": 38,
    "image" :"/service/bw3.jpg",
    "image2":"/service/bw4.jpg",
    "title": "window open",
    "status":"For sale",
    "price":"N20000",
    "features":"glass and steel",
    "condition":"New",
    "inventory":"33",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Kano",
    "area":"Kofa Shakir",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt"
  },
  {
    "id": 39,
    "image" :"/service/bssk1.jpg",
    "image2":"/service/bssk2.jpg",
    "title": "Sink",
    "status":"For Sale",
    "price":"N51000",
    "features":"ceramics and Wood",
    "condition":"New",
    "inventory":"5",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"Kotokarfey",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt"
  },
  {
    "id": 40,
    "image" :"/service/bssk3.jpg",
    "image2":"/service/bssk4.jpg",
    "title": "Sink",
    "status":"For Sale",
    "price":"N51000",
    "features":"ceramics and Wood",
    "condition":"New",
    "inventory":"15",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt"
  },
  {
    "id": 41,
    "image" :"/service/d1.jpg",
    "image2":"/service/d2.jpg",
    "title": "Steel Door",
    "status":"For Sale",
    "price":"N100000",
    "features":"high resolution HD",
    "condition":"New",
    "inventory":"31",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Kano",
    "area":"Dawakin kudo",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt"
  },
  {
    "id": 42,
    "image" :"/service/d44.jpg",
    "image2":"/service/d4.jpg",
    "title": "Door",
    "status":"For Sale",
    "price":"N500K",
    "features":"made in Nigeria",
    "condition":"New",
    "inventory":"11",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Niger",
    "area":"Mokwa",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt"
  },
  {
    "id": 43,
    "image" :"/service/carpet1.jpg",
    "image2":"/service/carpet2.jpg",
    "title": "Carpet",
    "status":"For Sale",
    "price":"N200000",
    "features":"Made in Turkey",
    "condition":"New",
    "inventory":"13",
    "tag":"Home And Garden",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt"
  },
  
];