export const MarketData = [
  {
    "id": 1,
    "image" :"/service/dell1.jpg",
    "image2":"/service/dell2.jpg",
    "title": "Dell Laptop",
    "status":"For Sale",
    "price":"N500K",
    "features":"11th Gen core i8 1trb ssd 32G",
    "condition":"Used",
    "inventory":"1",
    "tag":"Electronics and Gadgets",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 2,
    "image" :"/service/panel1.jpg",
    "image2":"/service/panel2.jpg",
    "title": "Solar Panels",
    "status":"For Sale",
    "price":"N1.5M - N3.3M",
    "features":"lithium core",
    "condition":"New",
    "inventory":"stocked",
    "tag":"Electronics and Gadgets",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 3,
    "image" :"/service/projector1.jpg",
    "image2":"/service/projector2.jpg",
    "title": "Projectors",
    "status":"For Lease",
    "price":"N1k per Hour",
    "features":"high resolution HD",
    "condition":"clean",
    "inventory":"3",
    "tag":"Electronics and Gadgets",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",
  },
  {
    "id": 4,
    "image" :"/service/camera1.jpg",
    "image2":"/service/camera2.jpg",
    "title": "Camera",
    "status":"For Lease",
    "price":"N1.5k per hour",
    "features":"Red Dragon",
    "condition":"clean",
    "inventory":"5",
    "tag":"Electronics and Gadgets",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",
  },
  {
    "id": 5,
    "image" :"/service/drill2.jpg",
    "image2":"/service/drill3.jpg",
    "title": "Power Drill",
    "status":"For Sale",
    "price":"N30k",
    "features":"Russian Made",
    "condition":"New",
    "inventory":"30",
    "tag":"Tools and Hardwares",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only", 
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt",   
  },
  {
    "id": 6,
    "image" :"/service/drill1.jpg",
    "image2":"/service/drill2.jpg",
    "title": "Power Drill",
    "status":"For Lease",
    "price":"N500 per hour",
    "features":"made in Russia",
    "condition":"clean",
    "inventory":"4",
    "tag":"Tools and Hardwares",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Aadan",
    "picture":"/service/6.jpg",
    "shop":"Aadanscmt",  
  },
  {
    "id": 7,
    "image" :"/service/bounce1.jpg",
    "image2":"/service/bounce2.jpg",
    "title": "bounce houses",
    "status":"For Lease",
    "price":"N2k per Hour",
    "features":"50 by 50 Square Meter",
    "condition":"clean Used",
    "inventory":"3",
    "tag":"Sports and Outdoors",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "picture":"/service/8.jpg",
    "shop":"Farajiscmt", 
  },
];