export const ShopData = [
  {
    "id": 1,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Micheal",
    "image" :"/service/7.jpg",
    "shopPic":"/service/ss1.jpg",
    "shopName":"Micheals",
    "shopId":"docId" ,
    "shopTag": "Fashion",
  },
  {
    "id": 2,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "image" :"/service/8.jpg",
    "shopPic":"/service/ss2.jpg",
    "shopName":"Farajis",
    "shopId":"docId" ,
    "shopTag": "Fashion", 
  },
  {
    "id": 3,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Isaac",
    "image" :"/service/6.jpg",
    "shopPic":"/service/ss3.jpg",
    "shopName":"Isaacs",
    "shopId":"docId" ,
    "shopTag": "Super Market"
  },
  {
    "id": 4,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Abraham",
    "image" :"/service/5.jpg",
    "shopPic":"/service/ss4.jpg",
    "shopName":"Abrahams",
    "shopId":"docId" ,
    "shopTag": "Electronics and Gadgets",
  },
  {
    "id": 5,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only", 
    "name":"David",
    "image" :"/service/3.jpg",
    "shopPic":"/service/ss5.jpg",
    "shopName":"Davids",   
    "shopId":"docId" ,
    "shopTag": "Babies and Toys",
  },
  {
    "id": 6,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Moses",
    "image" :"/service/2.jpg",
    "shopPic":"/service/ss6.jpg",
    "shopName":"Mosess",  
    "shopId":"docId" ,
    "shopTag": "Home and Building Construction",
  },
  {
    "id": 7,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Solomon",
    "image" :"/service/1.jpg",
    "shopPic":"/service/ss7.jpg",
    "shopName":"Solomons",
    "shopId":"docId" ,
    "shopTag": "Home and Building Construction",
  },
];