export const ShopData = [
  {
    "id": 1,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"shop 3 block 1 phase 1",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Micheal",
    "image" :"/service/7.jpg",
    "shopPic":"/service/ss1.jpg",
    "shopName":"MFash-Ionic",
    "shopId":"docId" ,
    "shopTag": "Fashion",
    "offers":"whole sales and retail",
    "market": "royal shopping complex",
    "account": "0000000001",
    "bankName": "xyz Bank",
    "accountName": "MFash-Ionic",
    "items": [
      {
        "id": 1,
        "image" :"/service/fc1.jpg",
        "image2":"/service/fc2.jpg",
        "title": "Black Face Cap",
        "status":"For Sale",
        "price":"N5000",
        "features":"cotton 100%",
        "condition":"new",
        "inventory":"1",
        "tag":"Fashion",
      },
      {
        "id": 2,
        "image" :"/service/fcc2.jpg",
        "image2":"/service/fcc3.jpg",
        "title": "Pain T shirt",
        "status":"For Sale",
        "price":"N3000",
        "features":"pure cotton",
        "condition":"New",
        "inventory":"stocked",
        "tag":"Fashion",
      },
      {
        "id": 3,
        "image" :"/service/fs1.jpg",
        "image2":"/service/fs2.jpg",
        "title": "black shoe",
        "status":"For sale",
        "price":"N35000",
        "features":"leather",
        "condition":"New",
        "inventory":"3",
        "tag":"Fashion",
      },
      {
        "id": 4,
        "image" :"/service/fs3.jpg",
        "image2":"/service/fs6.jpg",
        "title": "Brown Shoe",
        "status":"For Sale",
        "price":"N40000",
        "features":"skin",
        "condition":"new",
        "inventory":"5",
        "tag":"Fashion",
      },
      {
        "id": 5,
        "image" :"/service/ft1.jpg",
        "image2":"/service/ft2.jpg",
        "title": "Blue Jeans",
        "status":"For Sale",
        "price":"N3000",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"30",
        "tag":"Fashion",
       
      },
      {
        "id": 1,
        "image" :"/service/ft3.jpg",
        "image2":"/service/ft4.jpg",
        "title": "Used Jeans",
        "status":"For Sale",
        "price":"N1500",
        "features":"blue jeans",
        "condition":"Used",
        "inventory":"syocked",
        "tag":"Fashion",
      },
      {
        "id": 2,
        "image" :"/service/ft1.jpg",
        "image2":"/service/ft2.jpg",
        "title": "Blue Jeans",
        "status":"For Sale",
        "price":"N3000",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"30",
        "tag":"Fashion",
       
      },
      {
        "id": 3,
        "image" :"/service/fcl1.jpg",
        "image2":"/service/fcl2.jpg",
        "title": "Black Pain T shirt",
        "status":"For Sale",
        "price":"N3000",
        "features":"pure cotton",
        "condition":"New",
        "inventory":"stocked",
        "tag":"Fashion",
      },
      {
        "id": 4,
        "image" :"/service/fs3.jpg",
        "image2":"/service/fs6.jpg",
        "title": "Brown Shoe",
        "status":"For Sale",
        "price":"N40000",
        "features":"skin",
        "condition":"new",
        "inventory":"5",
        "tag":"Fashion",
      },
      {
        "id": 5,
        "image" :"/service/fc1.jpg",
        "image2":"/service/fc2.jpg",
        "title": "Black Face Cap",
        "status":"For Sale",
        "price":"N5000",
        "features":"cotton 100%",
        "condition":"new",
        "inventory":"1",
        "tag":"Fashion",
       
      },
    ],
  },
  {
    "id": 2,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"shop 2 block 4 phase 3",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Faraji",
    "image" :"/service/8.jpg",
    "shopPic":"/service/ss2.jpg",
    "shopName":"Aura & Styles",
    "shopId":"docId" ,
    "shopTag": "Fashion", 
    "offers":"whole sales and retail",
    "market": "okene central market",
    "account": "0000000001",
    "bankName": "xyz Bank",
    "accountName": "Aura & Styles",
    "items": [
      {
        "id": 1,
        "image" :"/service/ft3.jpg",
        "image2":"/service/ft4.jpg",
        "title": "Used Jeans",
        "status":"For Sale",
        "price":"N1500",
        "features":"blue jeans",
        "condition":"Used",
        "inventory":"syocked",
        "tag":"Fashion",
      },
      {
        "id": 2,
        "image" :"/service/ft1.jpg",
        "image2":"/service/ft2.jpg",
        "title": "Blue Jeans",
        "status":"For Sale",
        "price":"N3000",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"30",
        "tag":"Fashion",
       
      },
      {
        "id": 3,
        "image" :"/service/fcl1.jpg",
        "image2":"/service/fcl2.jpg",
        "title": "Black Pain T shirt",
        "status":"For Sale",
        "price":"N3000",
        "features":"pure cotton",
        "condition":"New",
        "inventory":"stocked",
        "tag":"Fashion",
      },
      {
        "id": 4,
        "image" :"/service/fs3.jpg",
        "image2":"/service/fs6.jpg",
        "title": "Brown Shoe",
        "status":"For Sale",
        "price":"N40000",
        "features":"skin",
        "condition":"new",
        "inventory":"5",
        "tag":"Fashion",
      },
      {
        "id": 5,
        "image" :"/service/fc1.jpg",
        "image2":"/service/fc2.jpg",
        "title": "Black Face Cap",
        "status":"For Sale",
        "price":"N5000",
        "features":"cotton 100%",
        "condition":"new",
        "inventory":"1",
        "tag":"Fashion",
       
      },
      {
        "id": 1,
        "image" :"/service/fc1.jpg",
        "image2":"/service/fc2.jpg",
        "title": "Black Face Cap",
        "status":"For Sale",
        "price":"N5000",
        "features":"cotton 100%",
        "condition":"new",
        "inventory":"1",
        "tag":"Fashion",
      },
      {
        "id": 2,
        "image" :"/service/fcc2.jpg",
        "image2":"/service/fcc3.jpg",
        "title": "Pain T shirt",
        "status":"For Sale",
        "price":"N3000",
        "features":"pure cotton",
        "condition":"New",
        "inventory":"stocked",
        "tag":"Fashion",
      },
      {
        "id": 3,
        "image" :"/service/fs1.jpg",
        "image2":"/service/fs2.jpg",
        "title": "black shoe",
        "status":"For sale",
        "price":"N35000",
        "features":"leather",
        "condition":"New",
        "inventory":"3",
        "tag":"Fashion",
      },
      {
        "id": 4,
        "image" :"/service/fs3.jpg",
        "image2":"/service/fs6.jpg",
        "title": "Brown Shoe",
        "status":"For Sale",
        "price":"N40000",
        "features":"skin",
        "condition":"new",
        "inventory":"5",
        "tag":"Fashion",
      },
      {
        "id": 5,
        "image" :"/service/ft1.jpg",
        "image2":"/service/ft2.jpg",
        "title": "Blue Jeans",
        "status":"For Sale",
        "price":"N3000",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"30",
        "tag":"Fashion",
       
      },
    ],
  },
  {
    "id": 3,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"shop 7 block 3 phase 7 ",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Isaac",
    "image" :"/service/6.jpg",
    "shopPic":"/service/ss3.jpg",
    "shopName":"One Mart",
    "shopId":"docId" ,
    "shopTag": "Super Market",
    "offers":"retail",
    "market": "central rail market",
    "account": "0000000001",
    "bankName": "xyz Bank",
    "accountName": "One Mart",
    "items": [
      {
        "id": 1,
        "image" :"/service/fish1.jpg",
        "image2":"/service/fish2.jpg",
        "title": "Ice Fish",
        "status":"For Sale",
        "price":"N1500 per kg",
        "features":"titus fish",
        "condition":"fresh",
        "inventory":"stoced",
        "tag":"Food and Provisions",
      },
      {
        "id": 2,
        "image" :"/service/bis1.jpg",
        "image2":"/service/bis2.jpg",
        "title": "Biscuit",
        "status":"For Sale",
        "price":"N2500 per pack",
        "features":"10 pis",
        "condition":"New",
        "inventory":"stocked",
        "tag":"Food and Provisions",
      },
      {
        "id": 3,
        "image" :"/service/meat1.jpg",
        "image2":"/service/meat2.jpg",
        "title": "Beaf",
        "status":"For sale",
        "price":"N1500 per kg",
        "features":"red meat halal",
        "condition":"fresh",
        "inventory":"stocked",
        "tag":"Food and Provisions",
      },
      {
        "id": 4,
        "image" :"/service/milk1.jpg",
        "image2":"/service/milk2.jpg",
        "title": "Milk Drink",
        "status":"For Sale",
        "price":"N300",
        "features":"meji milk",
        "condition":"fresh",
        "inventory":"30",
        "tag":"Food and Provisions"
       
      },
      {
        "id": 5,
        "image" :"/service/milo1.jpg",
        "image2":"/service/milo.jpg",
        "title": "Milo",
        "status":"For Sale",
        "price":"N5000",
        "features":"nestle 500g",
        "condition":"new",
        "inventory":"14",
        "tag":"Food and Provisions",
        
      },
      {
        "id": 6,
        "image" :"/service/rice1.jpg",
        "image2":"/service/rice2.jpg",
        "title": "Basmatic Rice",
        "status":"For Sale",
        "price":"N50000",
        "features":"Royal",
        "condition":"fresh",
        "inventory":"stock",
        "tag":"Food and Provisions",
        
      },
      {
        "id": 7,
        "image" :"/service/sos1.jpg",
        "image2":"/service/sos2.jpg",
        "title": "sosage",
        "status":"For Sale",
        "price":"N5000",
        "features":"Jonhsonville",
        "condition":"fresh",
        "inventory":"stock",
        "tag":"Food and Provisions",
        
      },
      {
        "id": 1,
        "image" :"/service/fc1.jpg",
        "image2":"/service/fc2.jpg",
        "title": "Black Face Cap",
        "status":"For Sale",
        "price":"N5000",
        "features":"cotton 100%",
        "condition":"new",
        "inventory":"1",
        "tag":"Fashion",
      },
      {
        "id": 2,
        "image" :"/service/fcc2.jpg",
        "image2":"/service/fcc3.jpg",
        "title": "Pain T shirt",
        "status":"For Sale",
        "price":"N3000",
        "features":"pure cotton",
        "condition":"New",
        "inventory":"stocked",
        "tag":"Fashion",
      },
      {
        "id": 3,
        "image" :"/service/fs1.jpg",
        "image2":"/service/fs2.jpg",
        "title": "black shoe",
        "status":"For sale",
        "price":"N35000",
        "features":"leather",
        "condition":"New",
        "inventory":"3",
        "tag":"Fashion",
      },
      {
        "id": 4,
        "image" :"/service/fs3.jpg",
        "image2":"/service/fs6.jpg",
        "title": "Brown Shoe",
        "status":"For Sale",
        "price":"N40000",
        "features":"skin",
        "condition":"new",
        "inventory":"5",
        "tag":"Fashion",
      },
      {
        "id": 5,
        "image" :"/service/ft1.jpg",
        "image2":"/service/ft2.jpg",
        "title": "Blue Jeans",
        "status":"For Sale",
        "price":"N3000",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"30",
        "tag":"Fashion",
       
      },
    ],
  },
  {
    "id": 4,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"shop 5 block 8 phase 2 ",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Abraham",
    "image" :"/service/5.jpg",
    "shopPic":"/service/ss4.jpg",
    "shopName":"GoTech",
    "shopId":"docId" ,
    "shopTag": "Electronics and Gadgets",
    "offers":"whole sales and retail",
    "market": "universal trading complex",
    "account": "0000000001",
    "bankName": "xyz Bank",
    "accountName": "GoTech",
    "items": [
      {
        "id": 1,
        "image" :"/service/dell1.jpg",
        "image2":"/service/dell2.jpg",
        "title": "Dell Laptop",
        "status":"For Sale",
        "price":"N500K",
        "features":"11th Gen core i8 1trb ssd 32G",
        "condition":"Used",
        "inventory":"1",
        "tag":"Electronics and Gadgets",
      },
      {
        "id": 2,
        "image" :"/service/panel1.jpg",
        "image2":"/service/panel2.jpg",
        "title": "Solar Panels",
        "status":"For Sale",
        "price":"N1.5M - N3.3M",
        "features":"lithium core",
        "condition":"New",
        "inventory":"stocked",
        "tag":"Electronics and Gadgets",
      },
      {
        "id": 3,
        "image" :"/service/projector1.jpg",
        "image2":"/service/projector2.jpg",
        "title": "Projectors",
        "status":"For Lease",
        "price":"N1k per Hour",
        "features":"high resolution HD",
        "condition":"clean",
        "inventory":"3",
        "tag":"Electronics and Gadgets",
      },
      {
        "id": 4,
        "image" :"/service/camera1.jpg",
        "image2":"/service/camera2.jpg",
        "title": "Camera",
        "status":"For Lease",
        "price":"N1.5k per hour",
        "features":"Red Dragon",
        "condition":"clean",
        "inventory":"5",
        "tag":"Electronics and Gadgets",
      },
      {
        "id": 5,
        "image" :"/service/drill2.jpg",
        "image2":"/service/drill3.jpg",
        "title": "Power Drill",
        "status":"For Sale",
        "price":"N30k",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"30",
        "tag":"Tools and Hardwares",
       
      },
      {
        "id": 6,
        "image" :"/service/drill1.jpg",
        "image2":"/service/drill2.jpg",
        "title": "Power Drill",
        "status":"For Lease",
        "price":"N500 per hour",
        "features":"made in Russia",
        "condition":"clean",
        "inventory":"4",
        "tag":"Tools and Hardwares",
        
      },
      {
        "id": 1,
        "image" :"/service/t1.jpg",
        "image2":"/service/t2.jpg",
        "title": "Black toy Benz",
        "status":"For Sale",
        "price":"N150000",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"13",
        "tag":"Toys and Games",
      },
      {
        "id": 2,
        "image" :"/service/t3.jpg",
        "image2":"/service/t4.jpg",
        "title": "White toy Car Benz",
        "status":"For Sale",
        "price":"N150000",
        "features":"Turkey Made",
        "condition":"New",
        "inventory":"stocked",
        "tag":"Toys and Games",
      },
      {
        "id": 3,
        "image" :"/service/tb1.jpg",
        "image2":"/service/tb2.jpg",
        "title": "Bicycle",
        "status":"For Slae",
        "price":"N70000",
        "features":"Made in China",
        "condition":"New",
        "inventory":"13",
        "tag":"Toys and Games",
      },
      {
        "id": 4,
        "image" :"/service/tsh1.jpg",
        "image2":"/service/tsh2.jpg",
        "title": "Roller-Skate",
        "status":"For Sale",
        "price":"N40000",
        "features":"Made in China",
        "condition":"New",
        "inventory":"5",
        "tag":"Toys and Games",
      },
      {
        "id": 5,
        "image" :"/service/tsr1.jpg",
        "image2":"/service/tsr2.jpg",
        "title": "skipping rope",
        "status":"For Sale",
        "price":"N3000",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"30",
        "tag":"Toys and Games",
       
      },
      {
        "id": 6,
        "image" :"/service/tsw1.jpg",
        "image2":"/service/tsw2.jpg",
        "title": "Nitendo Switch",
        "status":"For Sale",
        "price":"N250000",
        "features":"made in China",
        "condition":"New",
        "inventory":"4",
        "tag":"Toys and Games",
        
      },
      {
        "id": 7,
        "image" :"/service/bounce1.jpg",
        "image2":"/service/bounce2.jpg",
        "title": "bounce houses",
        "status":"For Lease",
        "price":"N2k per Hour",
        "features":"50 by 50 Square Meter",
        "condition":"clean Used",
        "inventory":"3",
        "tag":"Sports and Outdoors",
        
      },
    ],
  },
  {
    "id": 5,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"shop 1 block 2 phase 2",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only", 
    "name":"David",
    "image" :"/service/3.jpg",
    "shopPic":"/service/ss5.jpg",
    "shopName":"Kiddies Kind",   
    "shopId":"docId" ,
    "shopTag": "Babies and Toys",
    "offers":"retail",
    "market": "okene central market",
    "account": "0000000001",
    "bankName": "xyz Bank",
    "accountName": "Kiddies Kind",
    "items": [
      {
        "id": 1,
        "image" :"/service/t1.jpg",
        "image2":"/service/t2.jpg",
        "title": "Black toy Benz",
        "status":"For Sale",
        "price":"N150000",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"13",
        "tag":"Toys and Games",
      },
      {
        "id": 2,
        "image" :"/service/t3.jpg",
        "image2":"/service/t4.jpg",
        "title": "White toy Car Benz",
        "status":"For Sale",
        "price":"N150000",
        "features":"Turkey Made",
        "condition":"New",
        "inventory":"stocked",
        "tag":"Toys and Games",
      },
      {
        "id": 3,
        "image" :"/service/tb1.jpg",
        "image2":"/service/tb2.jpg",
        "title": "Bicycle",
        "status":"For Slae",
        "price":"N70000",
        "features":"Made in China",
        "condition":"New",
        "inventory":"13",
        "tag":"Toys and Games",
      },
      {
        "id": 4,
        "image" :"/service/tsh1.jpg",
        "image2":"/service/tsh2.jpg",
        "title": "Roller-Skate",
        "status":"For Sale",
        "price":"N40000",
        "features":"Made in China",
        "condition":"New",
        "inventory":"5",
        "tag":"Toys and Games",
      },
      {
        "id": 5,
        "image" :"/service/tsr1.jpg",
        "image2":"/service/tsr2.jpg",
        "title": "skipping rope",
        "status":"For Sale",
        "price":"N3000",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"30",
        "tag":"Toys and Games",
       
      },
      {
        "id": 6,
        "image" :"/service/tsw1.jpg",
        "image2":"/service/tsw2.jpg",
        "title": "Nitendo Switch",
        "status":"For Sale",
        "price":"N250000",
        "features":"made in China",
        "condition":"New",
        "inventory":"4",
        "tag":"Toys and Games",
        
      },
      {
        "id": 7,
        "image" :"/service/bounce1.jpg",
        "image2":"/service/bounce2.jpg",
        "title": "bounce houses",
        "status":"For Lease",
        "price":"N2k per Hour",
        "features":"50 by 50 Square Meter",
        "condition":"clean Used",
        "inventory":"3",
        "tag":"Sports and Outdoors",
        
      },
    ],
  },
  {
    "id": 6,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"shop 1 block 4 phase 2",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Moses",
    "image" :"/service/2.jpg",
    "shopPic":"/service/ss6.jpg",
    "shopName":"Fit & Finish",  
    "shopId":"docId" ,
    "shopTag": "Building and Home Fittings",
    "offers":"whole sales and retail",
    "market": "royal shopping complex",
    "account": "0000000001",
    "bankName": "xyz Bank",
    "accountName": "Fit and Finish",
    "items": [
      {
        "id": 1,
        "image" :"/service/d44.jpg",
        "image2":"/service/d4.jpg",
        "title": "Door",
        "status":"For Sale",
        "price":"N500K",
        "features":"made in Nigeria",
        "condition":"New",
        "inventory":"11",
        "tag":"Home And Garden",
      },
      {
        "id": 2,
        "image" :"/service/d33.jpg",
        "image2":"/service/d3.jpg",
        "title": "Bullet Proof Door",
        "status":"For Sale",
        "price":"N1.5M - N3.3M",
        "features":"heavy Proof Door",
        "condition":"New",
        "inventory":"stocked",
        "tag":"Home And Garden",
      },
      {
        "id": 3,
        "image" :"/service/d1.jpg",
        "image2":"/service/d2.jpg",
        "title": "Steel Door",
        "status":"For Sale",
        "price":"N100000",
        "features":"high resolution HD",
        "condition":"New",
        "inventory":"31",
        "tag":"Home And Garden",
      },
      {
        "id": 4,
        "image" :"/service/bssk1.jpg",
        "image2":"/service/bssk2.jpg",
        "title": "Sink",
        "status":"For Sale",
        "price":"N51000",
        "features":"ceramics and Wood",
        "condition":"New",
        "inventory":"5",
        "tag":"Home And Garden",
      },
      {
        "id": 5,
        "image" :"/service/bsst1.jpg",
        "image2":"/service/bsst2.jpg",
        "title": "Toilet Setter",
        "status":"For Sale",
        "price":"N70000",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"30",
        "tag":"Home And Garden",
       
      },
      {
        "id": 6,
        "image" :"/service/bw1.jpg",
        "image2":"/service/bw2.jpg",
        "title": "window push",
        "status":"For sale",
        "price":"N15000",
        "features":"made in Russia",
        "condition":"new",
        "inventory":"4",
        "tag":"Home And Garden",
        
      },
      {
        "id": 7,
        "image" :"/service/bw3.jpg",
        "image2":"/service/bw4.jpg",
        "title": "window open",
        "status":"For sale",
        "price":"N20000",
        "features":"glass and steel",
        "condition":"New",
        "inventory":"33",
        "tag":"Home And Garden",
        
      },
      {
        "id": 1,
        "image" :"/service/bsst3.jpg",
        "image2":"/service/bsst4.jpg",
        "title": "Turkey Toilet setter",
        "status":"For Sale",
        "price":"N500K",
        "features":"11th Gen Turk",
        "condition":"New",
        "inventory":"110",
        "tag":"Home And Garden",
      },
      {
        "id": 2,
        "image" :"/service/bw3.jpg",
        "image2":"/service/bw4.jpg",
        "title": "window open",
        "status":"For sale",
        "price":"N20000",
        "features":"glass and steel",
        "condition":"New",
        "inventory":"33",
        "tag":"Home And Garden",
      },
      {
        "id": 3,
        "image" :"/service/bssk1.jpg",
        "image2":"/service/bssk2.jpg",
        "title": "Sink",
        "status":"For Sale",
        "price":"N51000",
        "features":"ceramics and Wood",
        "condition":"New",
        "inventory":"5",
        "tag":"Home And Garden",
      },
      {
        "id": 4,
        "image" :"/service/bssk3.jpg",
        "image2":"/service/bssk4.jpg",
        "title": "Sink",
        "status":"For Sale",
        "price":"N51000",
        "features":"ceramics and Wood",
        "condition":"New",
        "inventory":"15",
        "tag":"Home And Garden",
      },
      {
        "id": 5,
        "image" :"/service/d1.jpg",
        "image2":"/service/d2.jpg",
        "title": "Steel Door",
        "status":"For Sale",
        "price":"N100000",
        "features":"high resolution HD",
        "condition":"New",
        "inventory":"31",
        "tag":"Home And Garden",
       
      },
      {
        "id": 6,
        "image" :"/service/d44.jpg",
        "image2":"/service/d4.jpg",
        "title": "Door",
        "status":"For Sale",
        "price":"N500K",
        "features":"made in Nigeria",
        "condition":"New",
        "inventory":"11",
        "tag":"Home And Garden",
        
      },
      {
        "id": 7,
        "image" :"/service/carpet1.jpg",
        "image2":"/service/carpet2.jpg",
        "title": "Carpet",
        "status":"For Sale",
        "price":"N200000",
        "features":"Made in Turkey",
        "condition":"New",
        "inventory":"13",
        "tag":"Home And Garden",
      },
    ],
  },
  {
    "id": 7,
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "address":"shop 3 block 1 phase 3",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "name":"Solomon",
    "image" :"/service/1.jpg",
    "shopPic":"/service/ss7.jpg",
    "shopName":"360 Builder",
    "shopId":"docId" ,
    "shopTag": "Building and Home Fittings",
    "offers":"whole sales and retail",
    "market": "okene central market",
    "account": "0000000001",
    "bankName": "xyz Bank",
    "accountName": "360 Builder",
    "items": [
      {
        "id": 1,
        "image" :"/service/bsst3.jpg",
        "image2":"/service/bsst4.jpg",
        "title": "Turkey Toilet setter",
        "status":"For Sale",
        "price":"N500K",
        "features":"11th Gen Turk",
        "condition":"New",
        "inventory":"110",
        "tag":"Home And Garden",
      },
      {
        "id": 2,
        "image" :"/service/bw3.jpg",
        "image2":"/service/bw4.jpg",
        "title": "window open",
        "status":"For sale",
        "price":"N20000",
        "features":"glass and steel",
        "condition":"New",
        "inventory":"33",
        "tag":"Home And Garden",
      },
      {
        "id": 3,
        "image" :"/service/bssk1.jpg",
        "image2":"/service/bssk2.jpg",
        "title": "Sink",
        "status":"For Sale",
        "price":"N51000",
        "features":"ceramics and Wood",
        "condition":"New",
        "inventory":"5",
        "tag":"Home And Garden",
      },
      {
        "id": 4,
        "image" :"/service/bssk3.jpg",
        "image2":"/service/bssk4.jpg",
        "title": "Sink",
        "status":"For Sale",
        "price":"N51000",
        "features":"ceramics and Wood",
        "condition":"New",
        "inventory":"15",
        "tag":"Home And Garden",
      },
      {
        "id": 5,
        "image" :"/service/d1.jpg",
        "image2":"/service/d2.jpg",
        "title": "Steel Door",
        "status":"For Sale",
        "price":"N100000",
        "features":"high resolution HD",
        "condition":"New",
        "inventory":"31",
        "tag":"Home And Garden",
       
      },
      {
        "id": 6,
        "image" :"/service/d44.jpg",
        "image2":"/service/d4.jpg",
        "title": "Door",
        "status":"For Sale",
        "price":"N500K",
        "features":"made in Nigeria",
        "condition":"New",
        "inventory":"11",
        "tag":"Home And Garden",
        
      },
      {
        "id": 7,
        "image" :"/service/carpet1.jpg",
        "image2":"/service/carpet2.jpg",
        "title": "Carpet",
        "status":"For Sale",
        "price":"N200000",
        "features":"Made in Turkey",
        "condition":"New",
        "inventory":"13",
        "tag":"Home And Garden",
      },
      {
        "id": 1,
        "image" :"/service/d44.jpg",
        "image2":"/service/d4.jpg",
        "title": "Door",
        "status":"For Sale",
        "price":"N500K",
        "features":"made in Nigeria",
        "condition":"New",
        "inventory":"11",
        "tag":"Home And Garden",
      },
      {
        "id": 2,
        "image" :"/service/d33.jpg",
        "image2":"/service/d3.jpg",
        "title": "Bullet Proof Door",
        "status":"For Sale",
        "price":"N1.5M - N3.3M",
        "features":"heavy Proof Door",
        "condition":"New",
        "inventory":"stocked",
        "tag":"Home And Garden",
      },
      {
        "id": 3,
        "image" :"/service/d1.jpg",
        "image2":"/service/d2.jpg",
        "title": "Steel Door",
        "status":"For Sale",
        "price":"N100000",
        "features":"high resolution HD",
        "condition":"New",
        "inventory":"31",
        "tag":"Home And Garden",
      },
      {
        "id": 4,
        "image" :"/service/bssk1.jpg",
        "image2":"/service/bssk2.jpg",
        "title": "Sink",
        "status":"For Sale",
        "price":"N51000",
        "features":"ceramics and Wood",
        "condition":"New",
        "inventory":"5",
        "tag":"Home And Garden",
      },
      {
        "id": 5,
        "image" :"/service/bsst1.jpg",
        "image2":"/service/bsst2.jpg",
        "title": "Toilet Setter",
        "status":"For Sale",
        "price":"N70000",
        "features":"Russian Made",
        "condition":"New",
        "inventory":"30",
        "tag":"Home And Garden",
       
      },
      {
        "id": 6,
        "image" :"/service/bw1.jpg",
        "image2":"/service/bw2.jpg",
        "title": "window push",
        "status":"For sale",
        "price":"N15000",
        "features":"made in Russia",
        "condition":"new",
        "inventory":"4",
        "tag":"Home And Garden",
        
      },
      {
        "id": 7,
        "image" :"/service/bw3.jpg",
        "image2":"/service/bw4.jpg",
        "title": "window open",
        "status":"For sale",
        "price":"N20000",
        "features":"glass and steel",
        "condition":"New",
        "inventory":"33",
        "tag":"Home And Garden",
        
      },
    ],
  },
];