export const VacancyData = [
  {
    "id": 1,
    "jobTitle" : "Software Engineering",
    "employer": "Soft CraftMan Tech",
    "responsibility":"Development and maintance of web app",
    "qualification":"Html, Css, Javascript, React, Typescript, Firebase",
    "salary":"N500K - N1.5M",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "addrees":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "opening":"30-05-2024",
    "closing":"30-05-2025",
    "type":"full-time"
  },
  {
    "id": 2,
    "jobTitle" : "Manager",
    "employer": "Soft CraftMan Tech",
    "responsibility":"Managing software Engineers on project ",
    "qualification":"5years experience on Html, Css, Javascript, React, Typescript, Firebase",
    "salary":"N500K - N1.5M",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "addrees":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "opening":"30-05-2024",
    "closing":"30-05-2025",
    "type":"full-time"
  },
  {
    "id": 3,
    "jobTitle" : "Accountant",
    "employer": "Soft CraftMan Tech",
    "responsibility":"Financial Accounting",
    "qualification":"Degree in Accounting",
    "salary":"N500K - N1.5M",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "addrees":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "opening":"30-05-2024",
    "closing":"30-05-2025",
    "type":"full-time"
  },

  {
    "id": 4,
    "jobTitle" : "Legal Adviser",
    "employer": "Soft CraftMan Tech",
    "responsibility":"Legality on every Task",
    "qualification":"Degree in Law",
    "salary":"N500K - N1.5M",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "addrees":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "opening":"30-05-2024",
    "closing":"30-05-2025",
    "type":"contract"
  },
  {
    "id": 5,
    "jobTitle" : "Admin Officer",
    "employer": "Soft CraftMan Tech",
    "responsibility":"Registration and Filing",
    "qualification":"Excel and Microsoft word",
    "salary":"N500K - N1.5M",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "addrees":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "opening":"30-05-2024",
    "closing":"30-05-2025",
    "type":"full-time"
  },
  {
    "id": 6,
    "jobTitle" : "Customer Care",
    "employer": "Soft CraftMan Tech",
    "responsibility":"Phone and Email Attendant",
    "qualification":"Human Relationship",
    "salary":"N500K - N1.5M",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "addrees":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "opening":"30-05-2024",
    "closing":"30-05-2025",
    "type":"contract"
  },
  {
    "id": 7,
    "jobTitle" : "Front Desk Officer",
    "employer": "Soft CraftMan Tech",
    "responsibility":"Office Reception",
    "qualification":"Human Relationship",
    "salary":"N500K - N1.5M",
    "country": "Nigeria",
    "state":"Kogi",
    "area":"okene",
    "addrees":"area 2 section 1 block 30 flat 2 oyo street garki",
    "email":"softcraftmantech@gmail.com",
    "phone":"07011111111, whatsapp only",
    "opening":"30-05-2024",
    "closing":"30-05-2025",
    "type":"contract"
  },
];