export const VendorsData = [
	{
		id: 1,
		name: "Auto Spray",
		src: "/service/auto_spray.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Aadan",
				src: "/service/1.jpg",
				address:
					"shop 1234 across the main market entrance opposite the office block, Zone 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Aamadu",
				src: "/service/2.jpg",
				address:
					"shop 5678 across the main market entrance opposite the complex, Area 8",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Abdoulaye",
				src: "/service/3.jpg",
				address:
					"shop 9101 across the main market entrance opposite the school block, District 12",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Aboubacar",
				src: "/service/4.jpg",
				address:
					"shop 2468 across the main market entrance opposite the hospital block, Zone 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Adamou",
				src: "/service/5.jpg",
				address:
					"shop 1357 across the main market entrance opposite the office block, Area 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ibrahima",
				src: "/service/6.jpg",
				address:
					"shop 8024 across the main market entrance opposite the complex, District 9",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Furaha",
				src: "/service/7.jpg",
				address:
					"shop 3690 across the main market entrance opposite the school block, Zone 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 2,
		name: "Car A.C",
		src: "/service/car_ac.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Faraji",
				src: "/service/8.jpg",
				address:
					"shop 3579 across the main market entrance opposite the office block in area 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Eseoghene",
				src: "/service/9.jpg",
				address:
					"shop 2468 across the main market entrance opposite the hospital block in area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Enyinnaya",
				src: "/service/10.jpg",
				address:
					"shop 8024 across the main market entrance opposite the complex in area 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Emem",
				src: "/service/11.jpg",
				address:
					"shop 9101 across the main market entrance opposite the school block in area 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Ekundayo",
				src: "/service/12.jpg",
				address:
					"shop 1234 across the main market entrance opposite the office block in area 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ekene",
				src: "/service/13.jpg",
				address:
					"shop 3690 across the main market entrance opposite the hospital block in area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ebrima",
				src: "/service/14.jpg",
				address:
					"shop 1357 across the main market entrance opposite the school block in area 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 3,
		name: "Mechanical",
		src: "/service/mechanic.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Faraji",
				src: "/service/8.jpg",
				address:
					"shop 3579 across the main market entrance opposite the school block, Zone 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Eseoghene",
				src: "/service/9.jpg",
				address:
					"shop 2468 across the main district plaza entrance opposite the complex, Area 6",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Enyinnaya",
				src: "/service/10.jpg",
				address:
					"shop 8024 across the main building capital entrance opposite the hospital block, District 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Emem",
				src: "/service/11.jpg",
				address:
					"shop 9101 across the main center entrance opposite the office block, Zone 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Ekundayo",
				src: "/service/12.jpg",
				address:
					"shop 1234 across the main town hall entrance opposite the school block, Area 9",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ekene",
				src: "/service/13.jpg",
				address:
					"shop 3690 across the main city mall entrance opposite the complex, District 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ebrima",
				src: "/service/14.jpg",
				address:
					"shop 1357 across the main state house entrance opposite the office block, Zone 8",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 4,
		name: "Panel beating",
		src: "/service/panel_beater.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Dalitso",
				src: "/service/6.jpg",
				address:
					"shop across the main market entrance opposite the bank block, Zone 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Dakarai",
				src: "/service/7.jpg",
				address:
					"shop across the main market entrance opposite the bank block, Area 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Cusmaan",
				src: "/service/8.jpg",
				address:
					"shop across the main market entrance opposite the bank block, District 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Chukwuebuka",
				src: "/service/9.jpg",
				address:
					"shop across the main market entrance opposite the bank block, Zone 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Idrissa",
				src: "/service/10.jpg",
				address:
					"shop across the main market entrance opposite the bank block, Area 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Imamu",
				src: "/service/11.jpg",
				address:
					"shop across the main market entrance opposite the bank block, District 9",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Issouf",
				src: "/service/12.jpg",
				address:
					"shop across the main market entrance opposite the bank block, Zone 6",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 5,
		name: "Re-Wiring",
		src: "/service/re-wire.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Dalitso",
				src: "/service/6.jpg",
				address:
					"shop 7854 across the main market entrance opposite the office zone, Zone 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Dakarai",
				src: "/service/7.jpg",
				address:
					"shop 3698 across the main market entrance opposite the zone block, Area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Cusmaan",
				src: "/service/8.jpg",
				address:
					"shop 1234 across the main market entrance opposite the complex zone, District 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Chukwuebuka",
				src: "/service/9.jpg",
				address:
					"shop 4567 across the main market entrance opposite the school zone, Zone 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Idrissa",
				src: "/service/10.jpg",
				address:
					"shop 9876 across the main market entrance opposite the hospital zone, Area 6",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Imamu",
				src: "/service/11.jpg",
				address:
					"shop 5432 across the main market entrance opposite the zone block, District 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Issouf",
				src: "/service/12.jpg",
				address:
					"shop 8901 across the main market entrance opposite the office zone, Zone 8",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 6,
		name: "Towwing",
		src: "/service/towing.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Kondwani",
				src: "/service/4.jpg",
				address:
					"shop across the main market entrance opposite the zone 123 block, Zone 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Kunto",
				src: "/service/5.jpg",
				address:
					"shop across the main market entrance opposite the zone 456 block, Area 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Kwaku",
				src: "/service/10.jpg",
				address:
					"shop across the main market entrance opposite the area 789 block, District 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Kwame",
				src: "/service/11.jpg",
				address:
					"shop across the main market entrance opposite the area 012 block, Zone 9",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Kwasi",
				src: "/service/12.jpg",
				address:
					"shop across the main market entrance opposite the zone 345 block, Area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Kyauta",
				src: "/service/13.jpg",
				address:
					"shop across the main market entrance opposite the zone 678 block, District 8",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Lassana",
				src: "/service/14.jpg",
				address:
					"shop across the main market entrance opposite the area 901 block, Zone 6",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 7,
		name: "Vulcanizing",
		src: "/service/vulcanizers.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Lawal",
				src: "/service/15.jpg",
				address:
					"shop across the main market entrance opposite the area 234 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "ELebogang",
				src: "/service/16.jpg",
				address:
					"shop across the main market entrance opposite the zone 567 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Lebohang",
				src: "/service/1.jpg",
				address:
					"shop across the main market entrance opposite the zone 890 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Lelisa",
				src: "/service/2.jpg",
				address:
					"shop across the main market entrance opposite the area 123 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Lencho",
				src: "/service/12.jpg",
				address:
					"shop across the main market entrance opposite the area 456 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "sego",
				src: "/service/13.jpg",
				address:
					"shop across the main market entrance opposite the zone 789 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Madalitso",
				src: "/service/14.jpg",
				address:
					"shop across the main market entrance opposite the zone 012 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 8,
		name: "wheel Balancing",
		src: "/service/wheel balance.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Mahamadou",
				src: "/service/15.jpg",
				address:
					"shop across the main market entrance opposite the zone 234 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Mamman",
				src: "/service/16.jpg",
				address:
					"shop across the main market entrance opposite the zone 567 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Mandlenkosi",
				src: "/service/1.jpg",
				address:
					"shop across the main market entrance opposite the area 890 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Moti",
				src: "/service/2.jpg",
				address:
					"shop across the main market entrance opposite the area 123 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Moussa",
				src: "/service/3.jpg",
				address:
					"shop across the main market entrance opposite the zone 456 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Moustapha",
				src: "/service/4.jpg",
				address:
					"shop across the main market entrance opposite the zone 789 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Mphatso",
				src: "/service/5.jpg",
				address:
					"shop across the main market entrance opposite the area 012 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},

	{
		id: 1,
		name: "AC,Fridge&Cooker",
		src: "/service/Ac, fridge and cooker.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Mpho",
				src: "/service/6.jpg",
				address:
					"shop across the main market entrance opposite the zone 234 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Muhammadu",
				src: "/service/7.jpg",
				address:
					"shop across the main market entrance opposite the zone 567 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Munyaradzi",
				src: "/service/8.jpg",
				address:
					"shop across the main market entrance opposite the area 890 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Musa",
				src: "/service/9.jpg",
				address:
					"shop across the main market entrance opposite the area 123 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Nkosana",
				src: "/service/10.jpg",
				address:
					"shop across the main market entrance opposite the zone 456 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Nkruma",
				src: "/service/11.jpg",
				address:
					"shop across the main market entrance opposite the zone 789 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Nsia",
				src: "/service/12.jpg",
				address:
					"shop across the main market entrance opposite the area 012 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 2,
		name: "Carpentery",
		src: "/service/carpenters.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Ochieng",
				src: "/service/13.jpg",
				address:
					"shop across the main market entrance opposite the area 234 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Odhiambo",
				src: "/service/9.jpg",
				address:
					"shop across the main market entrance opposite the zone 567 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Otieno",
				src: "/service/10.jpg",
				address:
					"shop across the main market entrance opposite the zone 890 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Otobong",
				src: "/service/11.jpg",
				address:
					"shop across the main market entrance opposite the area 123 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Oumar",
				src: "/service/12.jpg",
				address:
					"shop across the main market entrance opposite the area 456 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ousmane",
				src: "/service/13.jpg",
				address:
					"shop across the main market entrance opposite the zone 789 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Oyibo",
				src: "/service/14.jpg",
				address:
					"shop across the main market entrance opposite the zone 012 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 3,
		name: "Computer repair",
		src: "/service/computer.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Pilirani",
				src: "/service/7.jpg",
				address:
					"shop across the main market entrance opposite the area 567 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Rabiu",
				src: "/service/8.jpg",
				address:
					"shop across the main market entrance opposite the zone 890 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Rajabu",
				src: "/service/1.jpg",
				address:
					"shop across the main market entrance opposite the zone 012 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Refilwe",
				src: "/service/5.jpg",
				address:
					"shop across the main market entrance opposite the area 123 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Rudo",
				src: "/service/2.jpg",
				address:
					"shop across the main market entrance opposite the area 456 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ekene",
				src: "/service/3.jpg",
				address:
					"shop across the main market entrance opposite the zone 789 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ebrima",
				src: "/service/4.jpg",
				address:
					"shop across the main market entrance opposite the zone 234 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 4,
		name: "Dish installation",
		src: "/service/satelite.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Aadan",
				src: "/service/1.jpg",
				address:
					"shop across the main market entrance opposite the area 890 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Aamadu",
				src: "/service/2.jpg",
				address:
					"shop across the main market entrance opposite the zone 012 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Abdoulaye",
				src: "/service/3.jpg",
				address:
					"shop across the main market entrance opposite the area 345 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Aboubacar",
				src: "/service/4.jpg",
				address:
					"shop across the main market entrance opposite the zone 678 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Adamou",
				src: "/service/5.jpg",
				address:
					"shop across the main market entrance opposite the area 901 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ibrahima",
				src: "/service/6.jpg",
				address:
					"shop across the main market entrance opposite the zone 234 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Furaha",
				src: "/service/7.jpg",
				address:
					"shop across the main market entrance opposite the area 567 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 5,
		name: "Electrical",
		src: "/service/electrician.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Ebere",
				src: "/service/15.jpg",
				address:
					"shop across the main market entrance opposite the zone 890 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Dumisani",
				src: "/service/16.jpg",
				address:
					"shop across the main market entrance opposite the area 012 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Dayo",
				src: "/service/1.jpg",
				address:
					"shop across the main market entrance opposite the zone 345 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Dawit",
				src: "/service/2.jpg",
				address:
					"shop across the main market entrance opposite the area 678 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Ɗanlami",
				src: "/service/3.jpg",
				address:
					"shop across the main market entrance opposite the zone 901 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ɗanladi",
				src: "/service/4.jpg",
				address:
					"shop across the main market entrance opposite the area 234 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ɗanjuma",
				src: "/service/5.jpg",
				address:
					"shop across the main market entrance opposite the zone 567 block",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 6,
		name: "Fumigation",
		src: "/service/fumigator.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Dalitso",
				src: "/service/6.jpg",
				address:
					"shop 789 across the main market entrance opposite the complex block, Zone 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Dakarai",
				src: "/service/7.jpg",
				address:
					"shop 123 across the main bank entrance opposite the market block, Area 6",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Cusmaan",
				src: "/service/8.jpg",
				address:
					"shop 456 across the main complex entrance opposite the bank block, District 9",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Chukwuebuka",
				src: "/service/9.jpg",
				address:
					"shop 890 across the main market entrance opposite the complex block, Zone 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Idrissa",
				src: "/service/10.jpg",
				address:
					"shop 234 across the main bank entrance opposite the market block, Area 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Imamu",
				src: "/service/11.jpg",
				address:
					"shop 567 across the main complex entrance opposite the bank block, District 8",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Issouf",
				src: "/service/12.jpg",
				address:
					"shop 901 across the main market entrance opposite the complex block, Zone 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 7,
		name: "Gardening",
		src: "/service/gardeners.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Kunta",
				src: "/service/16.jpg",
				address:
					"shop 123 across the main market entrance opposite the bank block, area 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Kashim",
				src: "/service/15.jpg",
				address:
					"shop 456 across the main market entrance opposite the bank block,  zone 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Kwankaso",
				src: "/service/14.jpg",
				address:
					"shop 789 across the main market entrance opposite the bank block, area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Kabiru",
				src: "/service/13.jpg",
				address:
					"shop 890 across the main market entrance opposite the bank block, zone 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Kauna",
				src: "/service/12.jpg",
				address:
					"shop 234 across the main market entrance opposite the bank block, area 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Kamal",
				src: "/service/11.jpg",
				address:
					"shop 567 across the main market entrance opposite the bank block, zone 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "khalifa",
				src: "/service/10.jpg",
				address:
					"shop 901 across the main market entrance opposite the bank block, area 7, ",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 8,
		name: "Masonry",
		src: "/service/masonry.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Kondwani",
				src: "/service/4.jpg",
				address:
					"shop 123 across the main market entrance opposite the bank block, area 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Kunto",
				src: "/service/5.jpg",
				address:
					"shop 456 across the main market entrance opposite the bank block,  zone 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Kwaku",
				src: "/service/10.jpg",
				address:
					"shop 789 across the main market entrance opposite the bank block, area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Kwame",
				src: "/service/11.jpg",
				address:
					"shop 890 across the main market entrance opposite the bank block, zone 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Kwasi",
				src: "/service/12.jpg",
				address:
					"shop 234 across the main market entrance opposite the bank block, area 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Kyauta",
				src: "/service/13.jpg",
				address:
					"shop 567 across the main market entrance opposite the bank block, zone 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Lassana",
				src: "/service/14.jpg",
				address:
					"shop 901 across the main market entrance opposite the bank block, area 7, ",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 9,
		name: "Painting",
		src: "/service/painters.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Lawal",
				src: "/service/15.jpg",
				address:
					"shop 123 across the main market entrance opposite the bank block, area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "ELebogang",
				src: "/service/16.jpg",
				address:
					"shop 456 across the main market entrance opposite the bank block, zone 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Lebohang",
				src: "/service/1.jpg",
				address:
					"shop 789 across the main market entrance opposite the bank block, area 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Lelisa",
				src: "/service/2.jpg",
				address:
					"shop 890 across the main market entrance opposite the bank block, zone 6",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Lencho",
				src: "/service/12.jpg",
				address:
					"shop 234 across the main market entrance opposite the bank block, area 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "sego",
				src: "/service/13.jpg",
				address:
					"shop 567 across the main market entrance opposite the bank block, zone 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Madalitso",
				src: "/service/14.jpg",
				address:
					"shop 901 across the main market entrance opposite the bank block, area 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 10,
		name: "Phone repair",
		src: "/service/mobile_repair.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Kondwani",
				src: "/service/4.jpg",
				address:
					"shop 123 across the main market entrance opposite the bank block, area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Kunto",
				src: "/service/5.jpg",
				address:
					"shop 456 across the main market entrance opposite the bank block, zone 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Kwaku",
				src: "/service/10.jpg",
				address:
					"shop 789 across the main market entrance opposite the bank block, area 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Kwame",
				src: "/service/11.jpg",
				address:
					"shop 890 across the main market entrance opposite the bank block, zone 6",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Kwasi",
				src: "/service/12.jpg",
				address:
					"shop 234 across the main market entrance opposite the bank block, area 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Kyauta",
				src: "/service/13.jpg",
				address:
					"shop 567 across the main market entrance opposite the bank block, zone 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Lassana",
				src: "/service/14.jpg",
				address:
					"shop 901 across the main market entrance opposite the bank block, area 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 11,
		name: "Plumbing",
		src: "/service/plumbing.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Mpho",
				src: "/service/6.jpg",
				address:
					"shop across the main market entrance opposite the bank block, office zone 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Muhammadu",
				src: "/service/7.jpg",
				address:
					"shop across the main secretariat entrance opposite the bank block, area 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Munyaradzi",
				src: "/service/8.jpg",
				address:
					"shop across the main school entrance opposite the bank block, zone 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Musa",
				src: "/service/9.jpg",
				address:
					"shop across the main hospital entrance opposite the bank block, area 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Nkosana",
				src: "/service/10.jpg",
				address:
					"shop across the main market entrance opposite the bank block, zone 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Nkruma",
				src: "/service/11.jpg",
				address:
					"shop across the main office entrance opposite the bank block, area 6",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Nsia",
				src: "/service/12.jpg",
				address:
					"shop across the main secretariat entrance opposite the bank block, zone 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 12,
		name: "Recycling",
		src: "/service/rycyclers.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Aadan",
				src: "/service/1.jpg",
				address:
					"shop across the main office entrance opposite the bank block, area 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Aamadu",
				src: "/service/2.jpg",
				address:
					"shop across the main secretariat entrance opposite the bank block, zone 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Abdoulaye",
				src: "/service/3.jpg",
				address:
					"shop across the main school entrance opposite the bank block, area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Aboubacar",
				src: "/service/4.jpg",
				address:
					"shop across the main hospital entrance opposite the bank block, zone 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Adamou",
				src: "/service/5.jpg",
				address:
					"shop across the main office entrance opposite the bank block, area 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ibrahima",
				src: "/service/6.jpg",
				address:
					"shop across the main secretariat entrance opposite the bank block, zone 6",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Furaha",
				src: "/service/7.jpg",
				address:
					"shop across the main school entrance opposite the bank block, area 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},

	{
		id: 13,
		name: "Shoe repairing",
		src: "/service/shoe_repair.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Faraji",
				src: "/service/8.jpg",
				address:
					"shop across the main office entrance opposite the bank block, zone 8",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Eseoghene",
				src: "/service/9.jpg",
				address:
					"shop across the main secretariat entrance opposite the bank block, area 9",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Enyinnaya",
				src: "/service/10.jpg",
				address:
					"shop across the main school entrance opposite the bank block, zone 10",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Emem",
				src: "/service/11.jpg",
				address:
					"shop across the main hospital entrance opposite the bank block, area 11",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Ekundayo",
				src: "/service/12.jpg",
				address:
					"shop across the main office entrance opposite the bank block, zone 12",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ekene",
				src: "/service/6.jpg",
				address:
					"shop across the main secretariat entrance opposite the bank block, area 6",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ebrima",
				src: "/service/7.jpg",
				address:
					"shop across the main school entrance opposite the bank block, zone 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 14,
		name: "Solar panel",
		src: "/service/solar.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Ebere",
				src: "/service/15.jpg",
				address:
					"shop across the main office entrance opposite the bank block, area 15",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Dumisani",
				src: "/service/16.jpg",
				address:
					"shop across the main secretariat entrance opposite the bank block, zone 16",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Dayo",
				src: "/service/1.jpg",
				address:
					"shop across the main school entrance opposite the bank block, area 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Dawit",
				src: "/service/2.jpg",
				address:
					"shop across the main hospital entrance opposite the bank block, zone 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Ɗanlami",
				src: "/service/3.jpg",
				address:
					"shop across the main office entrance opposite the bank block, area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ɗanladi",
				src: "/service/4.jpg",
				address:
					"shop across the main secretariat entrance opposite the bank block, zone 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ɗanjuma",
				src: "/service/5.jpg",
				address:
					"shop across the main school entrance opposite the bank block, area 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 15,
		name: "Tiling",
		src: "/service/tiling.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Ebere",
				src: "/service/15.jpg",
				address:
					"shop 87 area 5 across the main office block entrance opposite the bank zone 12",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Dumisani",
				src: "/service/16.jpg",
				address:
					"shop 34 zone 9 across the main secretariat entrance opposite the bank area 22",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Dayo",
				src: "/service/11.jpg",
				address:
					"shop 51 area 14 across the main school entrance opposite the bank zone 67",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Dawit",
				src: "/service/12.jpg",
				address:
					"shop 72 zone 6 across the main hospital entrance opposite the bank area 39",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Ɗanlami",
				src: "/service/13.jpg",
				address:
					"shop 93 area 18 across the main office block entrance opposite the bank zone 81",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ɗanladi",
				src: "/service/14.jpg",
				address:
					"shop 45 zone 3 across the main secretariat entrance opposite the bank area 55",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ɗanjuma",
				src: "/service/15.jpg",
				address:
					"shop 29 area 11 across the main hospital entrance opposite the bank zone 46",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 16,
		name: "Welding",
		src: "/service/welding.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Aadan",
				src: "/service/10.jpg",
				address:
					"shop 67 across the main office block entrance opposite the bank block, Zone 35",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Aamadu",
				src: "/service/5.jpg",
				address:
					"shop 28 across the main secretariate entrance opposite the bank block, Area 42",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Abdoulaye",
				src: "/service/4.jpg",
				address:
					"shop 53 across the main school entrance opposite the bank block, Zone 16",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Aboubacar",
				src: "/service/3.jpg",
				address:
					"shop 46 across the main hospital entrance opposite the bank block, Area 78",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Adamou",
				src: "/service/2.jpg",
				address:
					"shop 82 across the main office block entrance opposite the bank block, Zone 29",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ibrahima",
				src: "/service/1.jpg",
				address:
					"shop 19 across the main secretariate entrance opposite the bank block, Area 91",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Furaha",
				src: "/service/7.jpg",
				address:
					"shop 74 across the main hospital entrance opposite the bank block, Zone 57",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},

	{
		id: 1,
		name: "Architectural",
		src: "/service/architecture.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Lawal",
				src: "/service/7.jpg",
				address:
					"shop 57 across the main office block entrance opposite the bank block, Zone 38",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "ELebogang",
				src: "/service/3.jpg",
				address:
					"shop 23 across the main secretariate entrance opposite the bank block, Area 71",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Lebohang",
				src: "/service/10.jpg",
				address:
					"shop 82 across the main school entrance opposite the bank block, Zone 19",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Lelisa",
				src: "/service/12.jpg",
				address:
					"shop 46 across the main hospital entrance opposite the bank block, Area 94",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Lencho",
				src: "/service/11.jpg",
				address:
					"shop 29 across the main office block entrance opposite the bank block, Zone 62",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "sego",
				src: "/service/12.jpg",
				address:
					"shop 16 across the main secretariate entrance opposite the bank block, Area 53",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Madalitso",
				src: "/service/13.jpg",
				address:
					"shop 73 across the main hospital entrance opposite the bank block, Zone 84",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 2,
		name: "Barbing",
		src: "/service/barbing.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Ochieng",
				src: "/service/2.jpg",
				address:
					"shop 63 across the main office block entrance opposite the bank block, Zone 17",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Odhiambo",
				src: "/service/3.jpg",
				address:
					"shop 28 across the main secretariate entrance opposite the bank block, Area 51",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Otieno",
				src: "/service/9.jpg",
				address:
					"shop 39 across the main school entrance opposite the bank block, Zone 86",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Otobong",
				src: "/service/6.jpg",
				address:
					"shop 94 across the main hospital entrance opposite the bank block, Area 23",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Oumar",
				src: "/service/2.jpg",
				address:
					"shop 72 across the main office block entrance opposite the bank block, Zone 44",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ousmane",
				src: "/service/8.jpg",
				address:
					"shop 57 across the main secretariate entrance opposite the bank block, Area 78",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Oyibo",
				src: "/service/5.jpg",
				address:
					"shop 35 across the main hospital entrance opposite the bank block, Zone 69",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 3,
		name: "Bbq",
		src: "/service/bbq.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Kondwani",
				src: "/service/4.jpg",
				address:
					"shop 53 across the main office block entrance opposite the bank block, Zone 92",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Kunto",
				src: "/service/5.jpg",
				address:
					"shop 29 across the main secretariate entrance opposite the bank block, Area 18",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Kwaku",
				src: "/service/1.jpg",
				address:
					"shop 66 across the main school entrance opposite the bank block, Zone 37",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Kwame",
				src: "/service/6.jpg",
				address:
					"shop 88 across the main hospital entrance opposite the bank block, Area 75",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Kwasi",
				src: "/service/7.jpg",
				address:
					"shop 44 across the main office block entrance opposite the bank block, Zone 59",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Kyauta",
				src: "/service/8.jpg",
				address:
					"shop 72 across the main secretariate entrance opposite the bank block, Area 21",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Lassana",
				src: "/service/9.jpg",
				address:
					"shop 17 across the main hospital entrance opposite the bank block, Zone 84",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 4,
		name: "Camera",
		src: "/service/camera.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Pilirani",
				src: "/service/15.jpg",
				address:
					"shop 17 across the main office block entrance opposite the bank block, Area 42",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Rabiu",
				src: "/service/16.jpg",
				address:
					"shop 92 across the main secretariate entrance opposite the bank block, Zone 76",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Rajabu",
				src: "/service/1.jpg",
				address:
					"shop 58 across the main school entrance opposite the bank block, Area 13",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Refilwe",
				src: "/service/2.jpg",
				address:
					"shop 33 across the main hospital entrance opposite the bank block, Zone 85",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Rudo",
				src: "/service/3.jpg",
				address:
					"shop 71 across the main office block entrance opposite the bank block, Area 29",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ekene",
				src: "/service/4.jpg",
				address:
					"shop 44 across the main secretariate entrance opposite the bank block, Zone 57",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ebrima",
				src: "/service/5.jpg",
				address:
					"shop 22 across the main school entrance opposite the bank block, Area 66",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 5,
		name: "Car Washing",
		src: "/service/car_wash.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Faraji",
				src: "/service/9.jpg",
				address:
					"shop 78 across the main secretariate entrance opposite the bank block, Zone 33",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Eseoghene",
				src: "/service/10.jpg",
				address:
					"shop 42 across the main school entrance opposite the bank block, Area 91",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Enyinnaya",
				src: "/service/11.jpg",
				address:
					"shop 26 across the main hospital entrance opposite the bank block, Zone 57",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Emem",
				src: "/service/12.jpg",
				address:
					"shop 55 across the main office block entrance opposite the bank block, Area 18",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Ekundayo",
				src: "/service/13.jpg",
				address:
					"shop 37 across the main secretariate entrance opposite the bank block, Zone 64",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ekene",
				src: "/service/14.jpg",
				address:
					"shop 89 across the main school entrance opposite the bank block, Area 42",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ebrima",
				src: "/service/15.jpg",
				address:
					"shop 21 across the main hospital entrance opposite the bank block, Zone 77",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},

	{
		id: 6,
		name: "Catering",
		src: "/service/catering.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Ochieng",
				src: "/service/13.jpg",
				address:
					"shop 68 across the main hospital entrance opposite the bank block, Zone 29",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Odhiambo",
				src: "/service/12.jpg",
				address:
					"shop 95 across the main secretariate entrance opposite the bank block, Area 77",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Otieno",
				src: "/service/11.jpg",
				address:
					"shop 21 across the main office block entrance opposite the bank block, Zone 46",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Otobong",
				src: "/service/1.jpg",
				address:
					"shop 53 across the main school entrance opposite the bank block, Area 83",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Oumar",
				src: "/service/2.jpg",
				address:
					"shop 77 across the main hospital entrance opposite the bank block, Zone 14",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ousmane",
				src: "/service/3.jpg",
				address:
					"shop 36 across the main office block entrance opposite the bank block, Area 92",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Oyibo",
				src: "/service/4.jpg",
				address:
					"shop 89 across the main secretariate entrance opposite the bank block, Zone 61",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 7,
		name: "Delivery",
		src: "/service/logistic.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Ebere",
				src: "/service/5.jpg",
				address:
					"shop 47 across the main secretariate entrance opposite the bank block, Zone 88",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Dumisani",
				src: "/service/16.jpg",
				address:
					"shop 82 across the main school entrance opposite the bank block, Area 51",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Dayo",
				src: "/service/1.jpg",
				address:
					"shop 29 across the main office block entrance opposite the bank block, Zone 73",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Dawit",
				src: "/service/12.jpg",
				address:
					"shop 56 across the main hospital entrance opposite the bank block, Area 19",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Ɗanlami",
				src: "/service/13.jpg",
				address:
					"shop 63 across the main market entrance opposite the bank block, Zone 37",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ɗanladi",
				src: "/service/14.jpg",
				address:
					"shop 41 across the main secretariate entrance opposite the bank block, Area 94",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ɗanjuma",
				src: "/service/15.jpg",
				address:
					"shop 78 across the main school entrance opposite the bank block, Zone 62",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 8,
		name: "Event Planning & Rental",
		src: "/service/event.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Itri",
				src: "/service/13.jpg",
				address:
					"shop 57 across the main secretariate entrance opposite the bank block, Area 22",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Jatau",
				src: "/service/11.jpg",
				address:
					"shop 84 across the main school entrance opposite the bank block, Zone 79",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Kelechi",
				src: "/service/7.jpg",
				address:
					"shop 32 across the main hospital entrance opposite the bank block, Area 66",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Kgosi",
				src: "/service/8.jpg",
				address:
					"shop 69 across the main office block entrance opposite the bank block, Zone 47",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Kidist",
				src: "/service/3.jpg",
				address:
					"shop 45 across the main market entrance opposite the bank block, Area 13",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Kirabo",
				src: "/service/4.jpg",
				address:
					"shop 78 across the main secretariate entrance opposite the bank block, Zone 58",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Kofi",
				src: "/service/9.jpg",
				address:
					"shop 51 across the main school entrance opposite the bank block, Area 91",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 9,
		name: "Gas delivery",
		src: "/service/gas.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Faraji",
				src: "/service/8.jpg",
				address:
					"shop 63 across the main secretariat entrance opposite the bank block, Area 54",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Eseoghene",
				src: "/service/9.jpg",
				address:
					"shop 29 across the main office block entrance opposite the bank block, Zone 82",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Enyinnaya",
				src: "/service/10.jpg",
				address:
					"shop 71 across the main hospital entrance opposite the bank block, Area 17",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Emem",
				src: "/service/11.jpg",
				address:
					"shop 42 across the main school entrance opposite the bank block, Zone 96",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Ekundayo",
				src: "/service/12.jpg",
				address:
					"shop 88 across the main market entrance opposite the bank block, Area 33",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ekene",
				src: "/service/6.jpg",
				address:
					"shop 19 across the main secretariat entrance opposite the bank block, Zone 70",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ebrima",
				src: "/service/7.jpg",
				address:
					"shop 50 across the main office block entrance opposite the bank block, Area 14",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 10,
		name: "Islamiya",
		src: "/service/islamiya.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Ochieng",
				src: "/service/7.jpg",
				address:
					"shop 18 across the main school entrance opposite the bank block, Zone 42",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Odhiambo",
				src: "/service/6.jpg",
				address:
					"shop 64 across the main office block entrance opposite the bank block, Area 83",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Otieno",
				src: "/service/5.jpg",
				address:
					"shop 27 across the main hospital entrance opposite the bank block, Zone 19",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Otobong",
				src: "/service/4.jpg",
				address:
					"shop 91 across the main secretariat entrance opposite the bank block, Area 75",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Oumar",
				src: "/service/3.jpg",
				address:
					"shop 55 across the main market entrance opposite the bank block, Zone 68",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ousmane",
				src: "/service/2.jpg",
				address:
					"shop 33 across the main office block entrance opposite the bank block, Area 22",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Oyibo",
				src: "/service/1.jpg",
				address:
					"shop 77 across the main hospital entrance opposite the bank block, Zone 93",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 11,
		name: "Home lessons",
		src: "/service/Home_lesson.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Mahamadou",
				src: "/service/15.jpg",
				address:
					"shop 42 across the main secretariat entrance opposite the bank block, Zone 77",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Mamman",
				src: "/service/16.jpg",
				address:
					"shop 83 across the main hospital entrance opposite the bank block, Area 64",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Mandlenkosi",
				src: "/service/1.jpg",
				address:
					"shop 19 across the main school entrance opposite the bank block, Zone 27",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Moti",
				src: "/service/2.jpg",
				address:
					"shop 75 across the main office block entrance opposite the bank block, Area 91",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Moussa",
				src: "/service/3.jpg",
				address:
					"shop 68 across the main market entrance opposite the bank block, Zone 55",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Moustapha",
				src: "/service/4.jpg",
				address:
					"shop 22 across the main secretariat entrance opposite the bank block, Area 33",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Mphatso",
				src: "/service/5.jpg",
				address:
					"shop 93 across the main hospital entrance opposite the bank block, Zone 77",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 12,
		name: "Laundry",
		src: "/service/laundry.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Lawal",
				src: "/service/15.jpg",
				address:
					"shop 58 across the main office block entrance opposite the bank block, Area 42",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "ELebogang",
				src: "/service/16.jpg",
				address:
					"shop 91 across the main secretariat entrance opposite the bank block, Zone 77",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Lebohang",
				src: "/service/1.jpg",
				address:
					"shop 26 across the main hospital entrance opposite the bank block, Area 19",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Lelisa",
				src: "/service/2.jpg",
				address:
					"shop 82 across the main school entrance opposite the bank block, Zone 65",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Lencho",
				src: "/service/12.jpg",
				address:
					"shop 37 across the main office block entrance opposite the bank block, Zone 23",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "sego",
				src: "/service/13.jpg",
				address:
					"shop 74 across the main secretariat entrance opposite the bank block, Area 58",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Madalitso",
				src: "/service/14.jpg",
				address:
					"shop 12 across the main hospital entrance opposite the bank block, Zone 31",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 13,
		name: "Medical",
		src: "/service/phamarcist.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Faraji",
				src: "/service/8.jpg",
				address:
					"shop 35 across the main office block entrance opposite the bank block, Area 17",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Eseoghene",
				src: "/service/9.jpg",
				address:
					"shop 61 across the main secretariat entrance opposite the bank block, Zone 48",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Enyinnaya",
				src: "/service/10.jpg",
				address:
					"shop 22 across the main hospital entrance opposite the bank block, Area 38",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Emem",
				src: "/service/11.jpg",
				address:
					"shop 79 across the main school entrance opposite the bank block, Zone 53",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Ekundayo",
				src: "/service/12.jpg",
				address:
					"shop 44 across the main office block entrance opposite the bank block, Area 29",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ekene",
				src: "/service/6.jpg",
				address:
					"shop 89 across the main secretariat entrance opposite the bank block, Zone 67",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ebrima",
				src: "/service/7.jpg",
				address:
					"shop 16 across the main hospital entrance opposite the bank block, Area 41",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 14,
		name: "Maid",
		src: "/service/maid.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Blessing",
				src: "/service/w1.jpg",
				address:
					"shop 29 across the main office block entrance opposite the bank block, Zone 15",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Precious",
				src: "/service/w2.jpg",
				address:
					"shop 61 across the main hospital entrance opposite the bank block, Area 37",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Favor",
				src: "/service/w3.jpg",
				address:
					"shop 42 across the main school entrance opposite the bank block, Zone 24",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Gift",
				src: "/service/w4.jpg",
				address:
					"shop 17 across the main office block entrance opposite the bank block, Area 49",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Beauty",
				src: "/service/w5.jpg",
				address:
					"shop 83 across the main secretariat entrance opposite the bank block, Zone 55",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Lovely",
				src: "/service/w6.jpg",
				address:
					"shop 56 across the main hospital entrance opposite the bank block, Area 28",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Peaceful",
				src: "/service/w7.jpg",
				address:
					"shop 95 across the main school entrance opposite the bank block, Zone 17",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 15,
		name: "Manicure",
		src: "/service/manicure.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Dalitso",
				src: "/service/2.jpg",
				address:
					"shop 35 across the main office block entrance opposite the bank block, Area 17",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Dakarai",
				src: "/service/7.jpg",
				address:
					"shop 61 across the main secretariat entrance opposite the bank block, Zone 48",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Cusmaan",
				src: "/service/4.jpg",
				address:
					"shop 22 across the main hospital entrance opposite the bank block, Area 38",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Chukwuebuka",
				src: "/service/3.jpg",
				address:
					"shop 79 across the main school entrance opposite the bank block, Zone 53",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Idrissa",
				src: "/service/1.jpg",
				address:
					"shop 44 across the main office block entrance opposite the bank block, Area 29",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Imamu",
				src: "/service/11.jpg",
				address:
					"shop 89 across the main secretariat entrance opposite the bank block, Zone 67",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Issouf",
				src: "/service/2.jpg",
				address:
					"shop 16 across the main hospital entrance opposite the bank block, Area 41",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},

	{
		id: 16,
		name: "Real-estate agents",
		src: "/service/agents.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Mahamadou",
				src: "/service/13.jpg",
				address:
					"shop across the main market entrance opposite the bank block Area 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Mamman",
				src: "/service/11.jpg",
				address:
					"shop across the main market entrance opposite the bank block Zone 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Mandlenkosi",
				src: "/service/6.jpg",
				address:
					"shop across the main market entrance opposite the bank block district 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Moti",
				src: "/service/2.jpg",
				address:
					"shop across the main market entrance opposite the bank block area 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Moussa",
				src: "/service/1.jpg",
				address:
					"shop across the main market entrance opposite the bank block Zone 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Moustapha",
				src: "/service/4.jpg",
				address:
					"shop across the main market entrance opposite the bank block District 5",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Mphatso",
				src: "/service/3.jpg",
				address:
					"shop across the main market entrance opposite the bank block Area 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 17,
		name: "Security",
		src: "/service/security.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Faraji",
				src: "/service/8.jpg",
				address:
					"shop across the main market entrance opposite the bank block Area 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Eseoghene",
				src: "/service/9.jpg",
				address:
					"shop across the main market entrance opposite the bank block District 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Enyinnaya",
				src: "/service/10.jpg",
				address:
					"shop across the main market entrance opposite the bank block Zone 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Emem",
				src: "/service/11.jpg",
				address:
					"shop across the main market entrance opposite the bank block Area 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Ekundayo",
				src: "/service/12.jpg",
				address:
					"shop across the main market entrance opposite the bank block Zone 9",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ekene",
				src: "/service/6.jpg",
				address:
					"shop across the main market entrance opposite the bank block Area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ebrima",
				src: "/service/7.jpg",
				address:
					"shop across the main market entrance opposite the bank block District 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
	{
		id: 18,
		name: "Tailoring",
		src: "/service/tailor.jpg",
		vendorsList: [
			{
				id: 1,
				name: "Pilirani",
				src: "/service/11.jpg",
				address:
					"shop across the main market entrance opposite the bank block Area 1",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 2,
				name: "Rabiu",
				src: "/service/12.jpg",
				address:
					"shop across the main market entrance opposite the bank block Zone 4",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 3,
				name: "Rajabu",
				src: "/service/1.jpg",
				address:
					"shop across the main market entrance opposite the bank block District 2",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 4,
				name: "Refilwe",
				src: "/service/2.jpg",
				address:
					"shop across the main market entrance opposite the bank block Zone 7",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 5,
				name: "Rudo",
				src: "/service/4.jpg",
				address:
					"shop across the main market entrance opposite the bank block Area 3",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 6,
				name: "Ekene",
				src: "/service/6.jpg",
				address:
					"shop across the main market entrance opposite the bank block Zone 9",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
			{
				id: 7,
				name: "Ebrima",
				src: "/service/8.jpg",
				address:
					"shop across the main market entrance opposite the bank block Area 11",
				contact: "07012345678",
				country:"Nigeria",
	      state: "kogi",
	      area:"okene",
			},
		],
	},
];
