import type { Metadata } from "next";
import styles from "./styles.module.css";
import UserNav from "@/components/nav/vendorNav/nav";
import { Suspense } from 'react'
import Loader from "@/components/load/load";




export const metadata: Metadata = {
  title: "Inter Linking Up Directory",
  description: "Generated by create next app",
  metadataBase: new URL('https://ilud.vercel.app'),
};

import type { Viewport } from 'next'
 
export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'cyan' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
  colorScheme: 'light',
}


export default function ProfileLayout(props: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <div className={styles.layoutBodyCover}>
        <Suspense fallback={<Loader/>}>
          {props.children}
          </Suspense>
        </div>
      </body>
    </html>
  );
}
